# Generated by Django 5.1.2 on 2024-11-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ("id",),
                "verbose_name": "service",
                "verbose_name_plural": "services",
            },
        ),
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.ImageField(upload_to="services"),
        ),
    ]
